set -g status-style "bg=#1e1e2e,fg=#cdd6f4"
set -g message-style "bg=#313244,fg=#cdd6f4"
set -g message-command-style "bg=#313244,fg=#cdd6f4"
set -g pane-border-style "fg=#313244"
set -g pane-active-border-style "fg=#cba6f7"

set -g @tmux-dotbar-bg "#1e1e2e"
set -g @tmux-dotbar-fg "#6c7086"
set -g @tmux-dotbar-fg-current "#cdd6f4"
set -g @tmux-dotbar-fg-session "#6c7086"
set -g @tmux-dotbar-fg-prefix "#cba6f7"
