set -g status-style "bg=#eff1f5,fg=#4c4f69"
set -g message-style "bg=#ccd0da,fg=#4c4f69"
set -g message-command-style "bg=#ccd0da,fg=#4c4f69"
set -g pane-border-style "fg=#ccd0da"
set -g pane-active-border-style "fg=#8839ef"

set -g @tmux-dotbar-bg "#eff1f5"
set -g @tmux-dotbar-fg "#9ca0b0"
set -g @tmux-dotbar-fg-current "#4c4f69"
set -g @tmux-dotbar-fg-session "#9ca0b0"
set -g @tmux-dotbar-fg-prefix "#8839ef"
