set nocompatible
set shell=/bin/bash

syntax enable
if exists('+termguicolors')
  let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
  let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
  set termguicolors
endif

if has('nvim')
  runtime! python_setup.vim
endif
" configure Vundle
filetype on " without this vim emits a zero exit status, later, because of :ft off
filetype off
let vimDir = '$HOME/.config/nvim'
" let &runtimepath .=',' . expand(vimDir . '/bundle/Vundle.vim')
set rtp+=~/.config/nvim/bundle/Vundle.vim/
call vundle#rc(expand($HOME.'/.config/nvim/bundle'))

" install Vundle bundles
if filereadable(expand("~/.config/nvim/nvimrc.bundles"))
  source ~/.config/nvim/nvimrc.bundles
endif

" ensure ftdetect et al work by including this after the Vundle stuff
filetype plugin indent on

" Enable basic mouse behavior such as resizing buffers.
set mouse=a

" in case you forgot to sudo
cnoremap w!! %!sudo tee > /dev/null %

" fdoc is yaml
autocmd BufRead,BufNewFile *.fdoc set filetype=yaml
" md is markdown
autocmd BufRead,BufNewFile *.md set filetype=markdown
autocmd BufRead,BufNewFile *.md set spell

" disable arrowkeys
nnoremap <up> <nop>
nnoremap <down> <nop>
nnoremap <left> <nop>
nnoremap <right> <nop>
inoremap <up> <nop>
inoremap <down> <nop>
inoremap <left> <nop>
inoremap <right> <nop>

set autoindent
set autoread                                                 " reload files when changed on disk, i.e. via `git checkout`
set backspace=2                                              " Fix broken backspace in some setups
set backupcopy=yes                                           " see :help crontab
set directory-=.                                             " don't store swapfiles in the current directory
set encoding=utf-8
set expandtab                                                " expand tabs to spaces
set hidden
set ignorecase                                               " case-insensitive search
set incsearch                                                " search as you type
set laststatus=4                                             " always show statusline
set list                                                     " show trailing whitespace
set listchars=tab:▸\ ,trail:▫
set noshowcmd
set noshowmode
set number                                                   " show line numbers
set relativenumber
set nocursorline
set ruler                                                    " show where you are
set scrolloff=3                                              " show context above/below cursorline
set shiftwidth=4                                             " normal mode indentation commands use 2 spaces
set showcmd
set cmdheight=2
set smartcase                                                " case-sensitive search if any caps
set softtabstop=4                                            " insert mode tab and backspace use 2 spaces
set tabstop=4                                                " actual tabs occupy 8 characters
set wildignore=log/**,node_modules/**,target/**,tmp/**,*.rbc
set wildmenu                                                 " show a navigable menu for tab completion
set wildmode=longest,list,full
set nobackup
set nowritebackup
set noswapfile
set updatetime=300
set shortmess+=c
set signcolumn=yes

" More natural splits
set splitbelow          " Horizontal split below current.
set splitright          " Vertical split to right of current.

" Spaces and tabs
set tabstop=2
set softtabstop=2
set backspace=2
set shiftwidth=2
set fileformat=unix

" Fix fish issues
set shell=sh
set path=$PWD/**

if filereadable(expand("~/.config/nvim/nvimrc.local"))
  source ~/.config/nvim/nvimrc.local
endif
