# Catppuccin theme state generated by macos/sync_theme.bash.

typeset -g __DOTFILES_THEME_FILE="${XDG_STATE_HOME:-$HOME/.local/state}/dotfiles-theme/zsh-theme.zsh"
typeset -g __DOTFILES_THEME_MTIME=""

__dotfiles_theme_mtime() {
  stat -f "%m" "$__DOTFILES_THEME_FILE" 2>/dev/null || stat -c "%Y" "$__DOTFILES_THEME_FILE" 2>/dev/null
}

__dotfiles_source_theme() {
  [[ -r "$__DOTFILES_THEME_FILE" ]] || return

  local mtime
  mtime="$(__dotfiles_theme_mtime)" || return

  if [[ "$mtime" != "$__DOTFILES_THEME_MTIME" ]]; then
    source "$__DOTFILES_THEME_FILE"
    __DOTFILES_THEME_MTIME="$mtime"
  fi
}

autoload -Uz add-zsh-hook
add-zsh-hook precmd __dotfiles_source_theme
__dotfiles_source_theme
